# Generated by Django 4.0.4 on 2022-04-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalib', '0002_remove_manga_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
