# Generated by Django 4.0.4 on 2022-05-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalib', '0003_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='id',
            field=models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False),
        ),
    ]
